export const TableData =[
    {
      name: 'Ralph Edwards',
      mrNo: 'SDF45678543',
      gender: 'Female',
      accession: '123RND',
      doctor: 'Cody Fisher',
      status: 'Completed',
    },
    {
      name: 'Jane Cooper',
      mrNo: 'XYZ12345678',
      gender: 'Male',
      accession: '987XYZ',
      doctor: 'Dr. Strange',
      status: 'Pending',
    },
    {
      name: 'Jane Cooper',
      mrNo: 'XYZ12345678',
      gender: 'Male',
      accession: '987XYZ',
      doctor: 'Dr. Strange',
      status: 'Pending',
    },
    {
      name: 'Jane Cooper',
      mrNo: 'XYZ12345678',
      gender: 'Male',
      accession: '987XYZ',
      doctor: 'Dr. Strange',
      status: 'Pending',
    },
    {
      name: 'Jane Cooper',
      mrNo: 'XYZ12345678',
      gender: 'Male',
      accession: '987XYZ',
      doctor: 'Dr. Strange',
      status: 'Completed',
    },
    {
      name: 'Jane Cooper',
      mrNo: 'XYZ12345678',
      gender: 'Male',
      accession: '987XYZ',
      doctor: 'Dr. Strange',
      status: 'Pending',
    },
    {
      name: 'Jane Cooper',
      mrNo: 'XYZ12345678',
      gender: 'Male',
      accession: '987XYZ',
      doctor: 'Dr. Strange',
      status: 'Pending',
    },
    {
      name: 'Jane Cooper',
      mrNo: 'XYZ12345678',
      gender: 'Male',
      accession: '987XYZ',
      doctor: 'Dr. Strange',
      status: 'Completed',
    },
    {
      name: 'Jane Cooper',
      mrNo: 'XYZ12345678',
      gender: 'Male',
      accession: '987XYZ',
      doctor: 'Dr. Strange',
      status: 'Pending',
    },
    {
      name: 'Jane Cooper',
      mrNo: 'XYZ12345678',
      gender: 'Male',
      accession: '987XYZ',
      doctor: 'Dr. Strange',
      status: 'Pending',
    },
  
  
  ];