export const TableData = [
    {
      name: 'Ralph Edwards',
      mrNo: 'SDF45678543',
      gender: 'Female',
      accession: '123RND',
      doctor: 'Cody Fisher',
      status: 'Completed',
    },
    {
      name: 'Jane Cooper',
      mrNo: 'XYZ12345678',
      gender: 'Male',
      accession: '987XYZ',
      doctor: 'Dr. Strange',
      status: 'Pending',
    },
    {
      name: 'Emily Chen',
      mrNo: 'ABC98765432',
      gender: 'Female',
      accession: '456DEF',
      doctor: 'Dr. Lee',
      status: 'Completed',
    },
    {
      name: 'Michael Brown',
      mrNo: 'GHI12345678',
      gender: 'Male',
      accession: '789JKL',
      doctor: 'Dr. Patel',
      status: 'Pending',
    },
    {
      name: 'Sarah Taylor',
      mrNo: 'MNO98765432',
      gender: 'Female',
      accession: '012PQR',
      doctor: 'Dr. Kim',
      status: 'Completed',
    },
    {
      name: 'David Lee',
      mrNo: 'STU12345678',
      gender: 'Male',
      accession: '345VWX',
      doctor: 'Dr. Davis',
      status: 'Pending',
    },
    {
      name: 'Olivia Martin',
      mrNo: 'YZA98765432',
      gender: 'Female',
      accession: '678BCD',
      doctor: 'Dr. Hall',
      status: 'Completed',
    },
    {
      name: 'William White',
      mrNo: 'EFG12345678',
      gender: 'Male',
      accession: '901HJK',
      doctor: 'Dr. Brooks',
      status: 'Pending',
    },
    {
      name: 'Ava Harris',
      mrNo: 'IJK98765432',
      gender: 'Female',
      accession: '234LMN',
      doctor: 'Dr. Jenkins',
      status: 'Completed',
    },
    {
      name: 'James Thompson',
      mrNo: 'OPQ12345678',
      gender: 'Male',
      accession: '567RST',
      doctor: 'Dr. Garcia',
      status: 'Pending',
    },
  ];